version: "3.8"
services:
  app:
    image: terramirum/explorer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_GRAPHQL_URL: ${NEXT_PUBLIC_GRAPHQL_URL}
      NEXT_PUBLIC_GRAPHQL_WS: ${NEXT_PUBLIC_GRAPHQL_WS}
      NEXT_PUBLIC_RPC_WEBSOCKET: ${NEXT_PUBLIC_RPC_WEBSOCKET}
      NEXT_PUBLIC_CHAIN_TYPE: ${NEXT_PUBLIC_CHAIN_TYPE}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      NEXT_PUBLIC_NETWORK_NAME: ${NEXT_PUBLIC_NETWORK_NAME}
      PROJECT_NAME: ${PROJECT_NAME}
    ports:
      - "3000:3000"